#include <stdio.h>
#include <iostream>
#include <conio.h>
#include <iomanip>
using namespace std;

int main(){
char a[30];
char b[30];
char c[30];
char d[30];
char e[30];
char f[30];
char g[30];
int h, i, j, k, l;
double m, n, o, p, q;
double r, s, t, u, v;
int w;
double x, y;
double aa, bb, cc, dd;

      cout<< "Enter Cashier ID: ";
    cin>>a;
    cout<< "Enter Cashier Name: ";
    cin>>b;
      cout<< "\nEnter Product 1: ";
    cin>>c;
    cout<< "Enter Quantity: ";
    cin>>h;
    cout<< "Enter Price: ";
    cin>>m;
      cout<< "\nEnter Product 2: ";
    cin>>d;
    cout<< "Enter Quantity: ";
    cin>>i;
    cout<< "Enter Price: ";
    cin>>n;
      cout<< "\nEnter Product 3: ";
    cin>>e;
    cout<< "Enter Quantity: ";
    cin>>j;
    cout<< "Enter Price: ";
    cin>>o;
      cout<< "\nEnter Product 4: ";
    cin>>f;
    cout<< "Enter Quantity: ";
    cin>>k;
    cout<< "Enter Price: ";
    cin>>p;
      cout<< "\nEnter Product 5: ";
    cin>>g;
    cout<< "Enter Quantity: ";
    cin>>l;
    cout<< "Enter Price: ";
    cin>>q;
    cout<<"\n===============================================================================================";
     cout<< setprecision(2) << fixed;
    cout<< "\n" << setw(51) << right << "AMA Supermarket";
    cout<< "\nCashier ID: " << a;
    cout<< "\nCashier Name: " << b;
    cout<<"\n===============================================================================================";
    cout<< "\n" << setw(20) << left << "Product" << setw(10) << right << "Quantity" << setw(25) << right << "Price" << setw(40) << right << "Total Price Per Product";
    cout<<"\n===============================================================================================";
r = (h*m);
    cout<< "\n" << setw(20) << left << c << setw(10) << right << h << setw(25) << right << m << setw(40) << right << r;
s = (i*n);
    cout<< "\n" << setw(20) << left << d << setw(10) << right << i << setw(25) << right << n << setw(40) << right << s;
t = (j*o);
    cout<< "\n" << setw(20) << left << e << setw(10) << right << j << setw(25) << right << o << setw(40) << right << t;
u = (k*p);
    cout<< "\n" << setw(20) << left << f << setw(10) << right << k << setw(25) << right << p << setw(40) << right << u;
v = (l*q);
    cout<< "\n" << setw(20) << left << g << setw(10) << right << l << setw(25) << right << q << setw(40) << right << v;
    cout<<"\n===============================================================================================";
w = (h+i+j+k+l);
    cout<< "\nQuantity: " << w;
x = (r+s+t+u+v);
    cout<< "\nTotal Price: " << x;
    cout<< "\nEnter Cash: ";
    cin>>y;
    cout<<"\n===============================================================================================";
      cout<< "\n" << setw(48) << right << "Receipt";
      cout<< "\n" << setw(51) << right << "AMA Supermarket";
      cout<< "\nCashier ID: " << a;
      cout<< "\nCashier Name: " << b;
    cout<<"\n===============================================================================================";
      cout<< "\n" << setw(20) << left << "Product" << setw(10) << right << "Quantity" << setw(25) << right << "Price" << setw(40) << right << "Total Price Per Product";
    cout<<"\n===============================================================================================";
      cout<< "\n" << setw(20) << left << c << setw(10) << right << h << setw(25) << right << m << setw(40) << right << r;
      cout<< "\n" << setw(20) << left << d << setw(10) << right << i << setw(25) << right << n << setw(40) << right << s;
      cout<< "\n" << setw(20) << left << e << setw(10) << right << j << setw(25) << right << o << setw(40) << right << t;
      cout<< "\n" << setw(20) << left << f << setw(10) << right << k << setw(25) << right << p << setw(40) << right << u;
      cout<< "\n" << setw(20) << left << g << setw(10) << right << l << setw(25) << right << q << setw(40) << right << v;
    cout<<"\n===============================================================================================";
aa = (x - bb);
      cout<< "\nGross: " << aa;
bb = (x*.12);
      cout<< "\nVAT Sales: " << bb;
cc = (aa + bb);
      cout<< "\nTotal: " << cc;
dd = (y - cc);
      cout<< "\nChange: " << dd;
cout<<"\n";
cout<<"\n";
cout<<"\nThank You for Shopping";
    return 0;
}
